language: sml

dist: trusty
sudo: required

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y --force-yes smlnj ml-yacc ml-lex ml-ulex
  - which pdflatex || sudo apt-get install texlive-full texlive-latex-extra

cache:
  directories:
  - /usr/bin

script:
  - chmod u+x script/test.sh
  - chmod u+x script/test_latex.sh
  - ./script/test_latex.sh
  - ./script/test.sh
