language: sml

dist: trusty
sudo: required


before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y --force-yes smlnj ml-yacc ml-lex ml-ulex

script:
  - make tests
  - sml @SMLload=test.x86-linux
