language: sml

before_install:
  - sudo apt-get update
  - sudo apt-get install libc6:i386
  - mkdir smlnj && cd smlnj
  - wget http://smlnj.cs.uchicago.edu/dist/working/110.81/config.tgz
  - gunzip < config.tgz | tar xf -
  - ./config/install.sh
  - which sml

script:
  - make tests
  - sml @SMLload=test.x86-linux
